apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: var-lib-mysql
  namespace: neromicare
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: var-lib-mysql
  resources:
    requests:
      storage: 10Gi